/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model.direktur;

import Connection.connect;
import Controller.*;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Yudo P
 */
public class dashboardDirectors extends javax.swing.JFrame {

    /**
     * Creates new form dashboardDirectors
     */
     private String username;
    private logindirekController control;
    private agendaController controlagenda;
    public dashboardDirectors(logindirekController controller,agendaController controlleragenda) {
        initComponents();
        this.control = controller;
        this.controlagenda = controlleragenda;
        control.getPemasukan(txtPenghasilan);
        control.getPengeluaran(txtPengeluaran);
        setExtendedState(MAXIMIZED_BOTH);
        control.closeFocus(txtPenghasilan, txtPengeluaran, txtNamekaryawan);
        controlagenda.tabel(tabelAgenda);
    }
    public dashboardDirectors(String username,logindirekController controller,agendaController controlleragenda) {
        initComponents();
        this.username = username;
        this.control = controller;
        this.controlagenda = controlleragenda;
        control.getPemasukan(txtPenghasilan);
        control.getPengeluaran(txtPengeluaran);
        txtNamekaryawan.setText(username.toUpperCase()); 
        control.closeFocus(txtPenghasilan, txtPengeluaran, txtNamekaryawan);
        setExtendedState(MAXIMIZED_BOTH);
        controlagenda.tabel(tabelAgenda);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNamekaryawan1 = new javax.swing.JTextField();
        txtNamekaryawan = new javax.swing.JTextField();
        txtPengeluaran = new javax.swing.JTextField();
        txtPenghasilan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelAgenda = new Component.Table();
        button2 = new Component.button();
        button1 = new Component.button();
        person = new Component.buttonradius();
        rekapteam = new Component.buttonradius();
        rekapacara = new Component.buttonradius();
        rekapkeuangan = new Component.buttonradius();
        finance = new Component.buttonradius();
        dataclient = new Component.buttonradius();
        dataacara = new Component.buttonradius();
        datateam = new Component.buttonradius();
        absensi = new Component.buttonradius();
        salaryrecap = new Component.buttonradius();
        salary = new Component.buttonradius();
        karyawanrecap = new Component.buttonradius();
        buttonradius2 = new Component.buttonradius();
        karyawan = new Component.buttonradius();
        jLabel2 = new javax.swing.JLabel();
        buttonradius1 = new Component.buttonradius();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamekaryawan1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNamekaryawan1.setForeground(new java.awt.Color(127, 199, 217));
        txtNamekaryawan1.setText("Karyawan");
        txtNamekaryawan1.setBorder(null);
        txtNamekaryawan1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtNamekaryawan1.setSelectedTextColor(new java.awt.Color(220, 242, 241));
        txtNamekaryawan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamekaryawan1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamekaryawan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 60, 170, 20));

        txtNamekaryawan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtNamekaryawan.setForeground(new java.awt.Color(54, 84, 134));
        txtNamekaryawan.setText("Aulia Dewi");
        txtNamekaryawan.setBorder(null);
        txtNamekaryawan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtNamekaryawan.setSelectedTextColor(new java.awt.Color(220, 242, 241));
        txtNamekaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamekaryawanActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamekaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 30, 170, 30));

        txtPengeluaran.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        txtPengeluaran.setForeground(new java.awt.Color(235, 71, 49));
        txtPengeluaran.setText("400.000.000");
        txtPengeluaran.setBorder(null);
        txtPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPengeluaranActionPerformed(evt);
            }
        });
        jPanel1.add(txtPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 280, 40));

        txtPenghasilan.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        txtPenghasilan.setForeground(new java.awt.Color(54, 84, 134));
        txtPenghasilan.setText("400.000.000");
        txtPenghasilan.setBorder(null);
        txtPenghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenghasilanActionPerformed(evt);
            }
        });
        jPanel1.add(txtPenghasilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 280, 40));

        tabelAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelAgenda);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 1200, 450));

        button2.setBorder(null);
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Lihat selengkapnya   ");
        button2.setBorderColor(new java.awt.Color(211, 39, 16));
        button2.setBorderPainted(false);
        button2.setColor(new java.awt.Color(211, 39, 16));
        button2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        button2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 640, 40));

        button1.setBackground(new java.awt.Color(54, 84, 134));
        button1.setBorder(null);
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Lihat selengkapnya   ");
        button1.setBorderColor(new java.awt.Color(54, 84, 134));
        button1.setBorderPainted(false);
        button1.setColor(new java.awt.Color(54, 84, 134));
        button1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        button1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 640, 40));

        person.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/person.png"))); // NOI18N
        person.setBorderColor(new java.awt.Color(255, 255, 255));
        person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personActionPerformed(evt);
            }
        });
        jPanel1.add(person, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 30, 70, 50));

        rekapteam.setBackground(new java.awt.Color(220, 242, 241));
        rekapteam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rekap team.png"))); // NOI18N
        rekapteam.setBorderColor(new java.awt.Color(220, 242, 241));
        rekapteam.setColor(new java.awt.Color(220, 242, 241));
        jPanel1.add(rekapteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 920, 120, 80));

        rekapacara.setBackground(new java.awt.Color(220, 242, 241));
        rekapacara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rekap acara.png"))); // NOI18N
        rekapacara.setBorderColor(new java.awt.Color(220, 242, 241));
        rekapacara.setColor(new java.awt.Color(220, 242, 241));
        jPanel1.add(rekapacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 920, 120, 80));

        rekapkeuangan.setBackground(new java.awt.Color(220, 242, 241));
        rekapkeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rekap keuangan.png"))); // NOI18N
        rekapkeuangan.setBorderColor(new java.awt.Color(220, 242, 241));
        rekapkeuangan.setColor(new java.awt.Color(220, 242, 241));
        jPanel1.add(rekapkeuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 920, 140, 80));

        finance.setBackground(new java.awt.Color(127, 199, 217));
        finance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/finance.png"))); // NOI18N
        finance.setBorderColor(new java.awt.Color(127, 199, 217));
        finance.setColor(new java.awt.Color(127, 199, 217));
        jPanel1.add(finance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 910, -1, 80));

        dataclient.setBackground(new java.awt.Color(127, 199, 217));
        dataclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/data client.png"))); // NOI18N
        dataclient.setBorderColor(new java.awt.Color(127, 199, 217));
        dataclient.setColor(new java.awt.Color(127, 199, 217));
        jPanel1.add(dataclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 910, -1, 80));

        dataacara.setBackground(new java.awt.Color(127, 199, 217));
        dataacara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/data acara.png"))); // NOI18N
        dataacara.setBorderColor(new java.awt.Color(127, 199, 217));
        dataacara.setColor(new java.awt.Color(127, 199, 217));
        jPanel1.add(dataacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 910, 80, 80));

        datateam.setBackground(new java.awt.Color(127, 199, 217));
        datateam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/data team.png"))); // NOI18N
        datateam.setBorderColor(new java.awt.Color(127, 199, 217));
        datateam.setColor(new java.awt.Color(127, 199, 217));
        jPanel1.add(datateam, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 910, 80, 80));

        absensi.setBackground(new java.awt.Color(127, 199, 217));
        absensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/absensi.png"))); // NOI18N
        absensi.setBorderColor(new java.awt.Color(127, 199, 217));
        absensi.setColor(new java.awt.Color(127, 199, 217));
        jPanel1.add(absensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 910, 80, 80));

        salaryrecap.setBackground(new java.awt.Color(220, 242, 241));
        salaryrecap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salary recap.png"))); // NOI18N
        salaryrecap.setBorderColor(new java.awt.Color(220, 242, 241));
        salaryrecap.setColor(new java.awt.Color(220, 242, 241));
        salaryrecap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryrecapActionPerformed(evt);
            }
        });
        jPanel1.add(salaryrecap, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 920, 100, 60));

        salary.setBackground(new java.awt.Color(220, 242, 241));
        salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salary.png"))); // NOI18N
        salary.setBorderColor(new java.awt.Color(220, 242, 241));
        salary.setColor(new java.awt.Color(220, 242, 241));
        jPanel1.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 920, 80, 60));

        karyawanrecap.setBackground(new java.awt.Color(220, 242, 241));
        karyawanrecap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/karyawan recap new.png"))); // NOI18N
        karyawanrecap.setBorderColor(new java.awt.Color(220, 242, 241));
        karyawanrecap.setColor(new java.awt.Color(220, 242, 241));
        jPanel1.add(karyawanrecap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 910, 190, 80));

        buttonradius2.setBackground(new java.awt.Color(127, 199, 217));
        buttonradius2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/karyawan recap.png"))); // NOI18N
        buttonradius2.setBorderColor(new java.awt.Color(127, 199, 217));
        buttonradius2.setColor(new java.awt.Color(127, 199, 217));
        jPanel1.add(buttonradius2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 910, 190, 80));

        karyawan.setBackground(new java.awt.Color(127, 199, 217));
        karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/karyawan.png"))); // NOI18N
        karyawan.setBorderColor(new java.awt.Color(127, 199, 217));
        karyawan.setColor(new java.awt.Color(127, 199, 217));
        jPanel1.add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 910, 80, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bg salary.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 910, -1, -1));

        buttonradius1.setBorderColor(new java.awt.Color(54, 84, 134));
        jPanel1.add(buttonradius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 20, 290, 70));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Desktop - 5 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamekaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamekaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamekaryawanActionPerformed

    private void txtPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPengeluaranActionPerformed

    private void txtPenghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenghasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenghasilanActionPerformed

    private void salaryrecapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryrecapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryrecapActionPerformed

    private void personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personActionPerformed

    private void txtNamekaryawan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamekaryawan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamekaryawan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                logindirekController control = new logindirekController();
                agendaController controlagenda = new agendaController();
                dashboardDirectors frame = new dashboardDirectors(control,controlagenda);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Component.buttonradius absensi;
    private Component.button button1;
    private Component.button button2;
    private Component.buttonradius buttonradius1;
    private Component.buttonradius buttonradius2;
    private Component.buttonradius dataacara;
    private Component.buttonradius dataclient;
    private Component.buttonradius datateam;
    private Component.buttonradius finance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private Component.buttonradius karyawan;
    private Component.buttonradius karyawanrecap;
    private Component.buttonradius person;
    private Component.buttonradius rekapacara;
    private Component.buttonradius rekapkeuangan;
    private Component.buttonradius rekapteam;
    private Component.buttonradius salary;
    private Component.buttonradius salaryrecap;
    private Component.Table tabelAgenda;
    private javax.swing.JTextField txtNamekaryawan;
    private javax.swing.JTextField txtNamekaryawan1;
    private javax.swing.JTextField txtPengeluaran;
    private javax.swing.JTextField txtPenghasilan;
    // End of variables declaration//GEN-END:variables
}
