/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model.direktur;

import Connection.connect;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Yudo P
 */
public class dashboardDirectors extends javax.swing.JFrame {

    /**
     * Creates new form dashboardDirectors
     */
    private String username;
    public dashboardDirectors() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        editablefield();
        setPenghasilan();
    }
    public dashboardDirectors(String username) {
        initComponents();
        this.username = username;
        txtNamekaryawan.setText(username.toUpperCase()); 
        editablefield();
        setPenghasilan();
    }
    int penghasilan,pengeluaran;
    private void editablefield(){
        txtPenghasilan.setEditable(false);
        txtPenghasilan.setFocusable(false);
        txtPengeluaran.setEditable(false);
        txtNamekaryawan.setEditable(false);
        txtPengeluaran.setFocusable(false);
        txtNamekaryawan.setFocusable(false);
    }
    private void setPenghasilan() {
    try {
        Connection kon = connect.koneksiDb();
        Statement st = kon.createStatement();
        String sql_tingkat = "SELECT * FROM finance_income";
        ResultSet rs = st.executeQuery(sql_tingkat);
        
        int penghasilan = 0; // Initialize penghasilan
        
        while (rs.next()) {
            penghasilan += rs.getInt("total"); // Accumulate total penghasilan
        }
        
        rs.close();
        st.close();
        kon.close(); // Close database connection
        
        // Format penghasilan using DecimalFormat
        DecimalFormat formatter = new DecimalFormat("#,##0");
        String formattedPenghasilan = formatter.format(penghasilan);
        
        txtPenghasilan.setText(formattedPenghasilan); // Set formatted penghasilan to text field
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNamekaryawan = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        txtPengeluaran = new javax.swing.JTextField();
        txtPenghasilan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new Component.Table();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamekaryawan.setBackground(new java.awt.Color(234, 234, 234));
        txtNamekaryawan.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtNamekaryawan.setForeground(new java.awt.Color(54, 84, 134));
        txtNamekaryawan.setText("Aulia Dewi");
        txtNamekaryawan.setBorder(null);
        txtNamekaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamekaryawanActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamekaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 40, 180, 20));

        jButton10.setBorder(null);
        jButton10.setOpaque(false);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 640, 30));

        jButton11.setBorder(null);
        jButton11.setOpaque(false);
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 640, 30));

        txtPengeluaran.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtPengeluaran.setForeground(new java.awt.Color(235, 71, 49));
        txtPengeluaran.setText("400.000.000");
        txtPengeluaran.setBorder(null);
        txtPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPengeluaranActionPerformed(evt);
            }
        });
        jPanel1.add(txtPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 280, 40));

        txtPenghasilan.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtPenghasilan.setForeground(new java.awt.Color(54, 84, 134));
        txtPenghasilan.setText("400.000.000");
        txtPenghasilan.setBorder(null);
        txtPenghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenghasilanActionPerformed(evt);
            }
        });
        jPanel1.add(txtPenghasilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 280, 40));

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 1190, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Group 5.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamekaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamekaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamekaryawanActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPengeluaranActionPerformed

    private void txtPenghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenghasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenghasilanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardDirectors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private Component.Table table3;
    private javax.swing.JTextField txtNamekaryawan;
    private javax.swing.JTextField txtPengeluaran;
    private javax.swing.JTextField txtPenghasilan;
    // End of variables declaration//GEN-END:variables
}
