/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model.direktur;

import Controller.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;

/**
 *
 * @author LENOVO
 */
public class dataAgenda extends javax.swing.JFrame {

    /**
     * Creates new form dataAgenda
     */
    private agendaController control;
    private String user;
    public dataAgenda(agendaController Controller) {
        this.control = Controller;
        initComponents();
        control.tabel(tabelAgenda);
        
    }
    public dataAgenda(agendaController Controller,String username) {
        this.control = Controller;
        initComponents();
        this.user = username;
        control.tabel(tabelAgenda);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        tampil = new Component.buttonradius();
        hapus = new Component.buttonradius();
        hapus1 = new Component.buttonradius();
        rekapacara = new Component.buttonradius();
        tambahteam = new Component.buttonradius();
        tambahteam1 = new Component.buttonradius();
        rekapkeuangan = new Component.buttonradius();
        rekapteam = new Component.buttonradius();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAgenda = new Component.Table();
        karyawan = new Component.buttonradius();
        buttonradius3 = new Component.buttonradius();
        salary = new Component.buttonradius();
        salaryrecap = new Component.buttonradius();
        absensi = new Component.buttonradius();
        datateam = new Component.buttonradius();
        dataacara = new Component.buttonradius();
        dataclient = new Component.buttonradius();
        finance = new Component.buttonradius();
        kembali = new Component.buttonradius();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tampil.setBackground(new java.awt.Color(127, 199, 217));
        tampil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/tp view.png"))); // NOI18N
        tampil.setBorderColor(new java.awt.Color(127, 199, 217));
        tampil.setColor(new java.awt.Color(127, 199, 217));

        hapus.setBackground(new java.awt.Color(127, 199, 217));
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/tp delete.png"))); // NOI18N
        hapus.setBorderColor(new java.awt.Color(127, 199, 217));
        hapus.setColor(new java.awt.Color(127, 199, 217));

        hapus1.setBackground(new java.awt.Color(127, 199, 217));
        hapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/tp edit.png"))); // NOI18N
        hapus1.setBorderColor(new java.awt.Color(127, 199, 217));
        hapus1.setColor(new java.awt.Color(127, 199, 217));

        rekapacara.setBackground(new java.awt.Color(220, 242, 241));
        rekapacara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rekap acara.png"))); // NOI18N
        rekapacara.setBorderColor(new java.awt.Color(220, 242, 241));
        rekapacara.setColor(new java.awt.Color(220, 242, 241));

        tambahteam.setBackground(new java.awt.Color(127, 199, 217));
        tambahteam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/tambah agenda.png"))); // NOI18N
        tambahteam.setBorderColor(new java.awt.Color(127, 199, 217));
        tambahteam.setColor(new java.awt.Color(127, 199, 217));
        tambahteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahteamActionPerformed(evt);
            }
        });

        tambahteam1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Complete Agenda.png"))); // NOI18N
        tambahteam1.setBorderColor(new java.awt.Color(127, 199, 217));
        tambahteam1.setColor(new java.awt.Color(127, 199, 217));

        rekapkeuangan.setBackground(new java.awt.Color(220, 242, 241));
        rekapkeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rekap keuangan.png"))); // NOI18N
        rekapkeuangan.setBorderColor(new java.awt.Color(220, 242, 241));
        rekapkeuangan.setColor(new java.awt.Color(220, 242, 241));

        rekapteam.setBackground(new java.awt.Color(220, 242, 241));
        rekapteam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rekap team.png"))); // NOI18N
        rekapteam.setBorderColor(new java.awt.Color(220, 242, 241));
        rekapteam.setColor(new java.awt.Color(220, 242, 241));

        tabelAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelAgenda);

        karyawan.setBackground(new java.awt.Color(127, 199, 217));
        karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/karyawan.png"))); // NOI18N
        karyawan.setBorderColor(new java.awt.Color(127, 199, 217));
        karyawan.setColor(new java.awt.Color(127, 199, 217));
        karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanActionPerformed(evt);
            }
        });

        buttonradius3.setBackground(new java.awt.Color(127, 199, 217));
        buttonradius3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/karyawan recap.png"))); // NOI18N
        buttonradius3.setBorderColor(new java.awt.Color(127, 199, 217));
        buttonradius3.setColor(new java.awt.Color(127, 199, 217));

        salary.setBackground(new java.awt.Color(220, 242, 241));
        salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salary.png"))); // NOI18N
        salary.setBorderColor(new java.awt.Color(220, 242, 241));
        salary.setColor(new java.awt.Color(220, 242, 241));
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });

        salaryrecap.setBackground(new java.awt.Color(220, 242, 241));
        salaryrecap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salary recap.png"))); // NOI18N
        salaryrecap.setBorderColor(new java.awt.Color(220, 242, 241));
        salaryrecap.setColor(new java.awt.Color(220, 242, 241));

        absensi.setBackground(new java.awt.Color(127, 199, 217));
        absensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/absensi.png"))); // NOI18N
        absensi.setBorderColor(new java.awt.Color(127, 199, 217));
        absensi.setColor(new java.awt.Color(127, 199, 217));
        absensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absensiActionPerformed(evt);
            }
        });

        datateam.setBackground(new java.awt.Color(127, 199, 217));
        datateam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/data team.png"))); // NOI18N
        datateam.setBorderColor(new java.awt.Color(127, 199, 217));
        datateam.setColor(new java.awt.Color(127, 199, 217));
        datateam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datateamActionPerformed(evt);
            }
        });

        dataacara.setBackground(new java.awt.Color(127, 199, 217));
        dataacara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/data acara.png"))); // NOI18N
        dataacara.setBorderColor(new java.awt.Color(127, 199, 217));
        dataacara.setColor(new java.awt.Color(127, 199, 217));
        dataacara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataacaraActionPerformed(evt);
            }
        });

        dataclient.setBackground(new java.awt.Color(127, 199, 217));
        dataclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/data client.png"))); // NOI18N
        dataclient.setBorderColor(new java.awt.Color(127, 199, 217));
        dataclient.setColor(new java.awt.Color(127, 199, 217));
        dataclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataclientActionPerformed(evt);
            }
        });

        finance.setBackground(new java.awt.Color(127, 199, 217));
        finance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/finance.png"))); // NOI18N
        finance.setBorderColor(new java.awt.Color(127, 199, 217));
        finance.setColor(new java.awt.Color(127, 199, 217));

        kembali.setBackground(new java.awt.Color(220, 242, 241));
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/kembali.png"))); // NOI18N
        kembali.setBorderColor(new java.awt.Color(220, 242, 241));
        kembali.setColor(new java.awt.Color(220, 242, 241));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bg salary.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/data acara form.png"))); // NOI18N

        DesktopPane.setLayer(tampil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(hapus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(hapus1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(rekapacara, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(tambahteam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(tambahteam1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(rekapkeuangan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(rekapteam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(karyawan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(buttonradius3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(salary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(salaryrecap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(absensi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(datateam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(dataacara, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(dataclient, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(finance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(kembali, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(buttonradius3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(1000, 1000, 1000)
                .addComponent(dataclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(1140, 1140, 1140)
                .addComponent(finance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(860, 860, 860)
                .addComponent(dataacara, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(salaryrecap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(1020, 1020, 1020)
                .addComponent(hapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(900, 900, 900)
                .addComponent(tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(1470, 1470, 1470)
                .addComponent(rekapkeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(1095, 1095, 1095)
                .addComponent(tambahteam, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(1410, 1410, 1410)
                .addComponent(tambahteam1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(960, 960, 960)
                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(720, 720, 720)
                .addComponent(datateam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel6))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(1640, 1640, 1640)
                .addComponent(rekapacara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(1770, 1770, 1770)
                .addComponent(rekapteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(absensi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(buttonradius3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(dataclient, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(finance, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(dataacara, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(920, 920, 920)
                .addComponent(salaryrecap, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(hapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(920, 920, 920)
                .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(tampil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(920, 920, 920)
                .addComponent(rekapkeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(tambahteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addComponent(tambahteam1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(datateam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(jLabel6))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(920, 920, 920)
                .addComponent(rekapacara, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(920, 920, 920)
                .addComponent(rekapteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(absensi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(DesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanActionPerformed
        // TODO add your handling code here:
        user = "";
        karyawanController karControl = new karyawanController();
        dataKaryawan frame = new dataKaryawan(karControl,user);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_karyawanActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
        user="";
        salaryController salaryControl = new salaryController();
        salaryKaryawan frame = new salaryKaryawan(salaryControl,user);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_salaryActionPerformed

    private void absensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absensiActionPerformed
        // TODO add your handling code here:
        user = "";
        AbsensiController absenControl = new AbsensiController();
        absensiKaryawan frame = new absensiKaryawan(absenControl);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_absensiActionPerformed

    private void datateamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datateamActionPerformed
        // TODO add your handling code here:
        user = "";
        teamController teamControl = new teamController();
        dataTeam frame = new dataTeam(teamControl,user);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_datateamActionPerformed

    private void dataacaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataacaraActionPerformed
        // TODO add your handling code here:
        user = "";
        agendaController agenControl = new agendaController();
        dataAgenda frame = new dataAgenda(agenControl,user);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_dataacaraActionPerformed

    private void dataclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataclientActionPerformed
        // TODO add your handling code here:
        user = "";
        klienController klienControl = new klienController();
        dataKlien frame = new dataKlien(klienControl,user);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_dataclientActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        user = "";
        agendaController agenControl = new agendaController();
        logindirekController loginControl = new logindirekController();
        dashboardDirectors frame = new dashboardDirectors(user,loginControl,agenControl);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void tambahteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahteamActionPerformed
        // TODO add your handling code here:
         JInternalFrame frame = new JInternalFrame("add Agenda", true, true, true, true);

// framekan komponen-komponen ke dalam JInternalFrame
agendaController agencontrol = new agendaController();
addAgenda panel = new addAgenda(agencontrol);
panel.add(new JLabel("Ini adalah panel yang mengambang"));
frame.add(panel);

// Atur ukuran JInternalFrame
frame.setSize(657,950);

// Mendapatkan ukuran layar
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
int screenWidth = (int) screenSize.getWidth();
int screenHeight = (int) screenSize.getHeight();

// Mendapatkan posisi x dan y untuk menempatkan internal frame di tengah layar
int x = (screenWidth - frame.getWidth()) / 2;
int y = (screenHeight - frame.getHeight()) / 2;

// Set lokasi internal frame di tengah layar
frame.setLocation(x, y);

// Tampilkan JInternalFrame
frame.setVisible(true);

// framekan JInternalFrame ke dalam JDesktopPane
DesktopPane.add(frame);

// Agar JInternalFrame bisa ditampilkan di depan
frame.toFront();

try {
    frame.setSelected(true);
} catch (java.beans.PropertyVetoException e) {
    System.out.println("Exception: " + e.getMessage());
} 
    }//GEN-LAST:event_tambahteamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              agendaController control = new agendaController();
                dataAgenda frame = new dataAgenda(control);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private Component.buttonradius absensi;
    private Component.buttonradius buttonradius3;
    private Component.buttonradius dataacara;
    private Component.buttonradius dataclient;
    private Component.buttonradius datateam;
    private Component.buttonradius finance;
    private Component.buttonradius hapus;
    private Component.buttonradius hapus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private Component.buttonradius karyawan;
    private Component.buttonradius kembali;
    private Component.buttonradius rekapacara;
    private Component.buttonradius rekapkeuangan;
    private Component.buttonradius rekapteam;
    private Component.buttonradius salary;
    private Component.buttonradius salaryrecap;
    private Component.Table tabelAgenda;
    private Component.buttonradius tambahteam;
    private Component.buttonradius tambahteam1;
    private Component.buttonradius tampil;
    // End of variables declaration//GEN-END:variables
}
