/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model.direktur;



import Connection.*;
import Controller.logindirekController;
import Controller.registerdirekController;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Yudo P
 */
public class loginDirectors extends javax.swing.JFrame {

    /**
     * Creates new form loginDirectors
     */
    private logindirekController control;
    public loginDirectors(logindirekController controller) {
        this.control = controller;
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    public loginDirectors() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
////     String username,password,level;
////     private String hashPassword(String password) throws NoSuchAlgorithmException {
////        try {
////            MessageDigest digest = MessageDigest.getInstance("MD5");
////            byte[] hash = digest.digest(password.getBytes());
////            StringBuilder hexString = new StringBuilder();
////            
////            for (byte b : hash) {
////                String hex = Integer.toHexString(0xff & b);
////                if (hex.length() == 1) {
////                    hexString.append('0');
////                }
////                hexString.append(hex);
////            }
////            return hexString.toString();
////        } catch (NoSuchAlgorithmException e) {
////            throw new NoSuchAlgorithmException("Hashing algorithm not found.");
////        }
////    }
////    
////    private boolean login(String email, String password) {
////        try (Connection connection = connect.koneksiDb()) {
////            String sql = "SELECT * FROM account WHERE email = ? AND password = ? AND level = 'director'";
////            try (PreparedStatement statement = connection.prepareStatement(sql)) {
////                statement.setString(1, email);
////                statement.setString(2, hashPassword(password)); // Hash password sebelum membandingkan
////                try (ResultSet resultSet = statement.executeQuery()) {
////                    if (resultSet.next()) {
////                        level = resultSet.getString("level");
////                        JOptionPane.showMessageDialog(null, "Login Success, Selamat Datang " + email);
////                        username = email;
////                        dashboardDirectors dash = new dashboardDirectors(username);
////                        dash.setVisible(true);
////                        return true;
////                    } else {
////                        JOptionPane.showMessageDialog(null, "Email atau password salah");
////                        return false;
////                    }
////                }
////            }
////        } catch (SQLException | NoSuchAlgorithmException e) {
////            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
////            return false;
////        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        buttonradius1 = new Component.buttonradius();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(127, 199, 217));
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1363, 412, 370, 40));

        txtPass.setBackground(new java.awt.Color(127, 199, 217));
        txtPass.setBorder(null);
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 500, 370, 40));

        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 790, 100, 30));

        buttonradius1.setForeground(new java.awt.Color(170, 187, 232));
        buttonradius1.setText("MASUK");
        buttonradius1.setBorderColor(new java.awt.Color(54, 84, 134));
        buttonradius1.setColor(new java.awt.Color(54, 84, 134));
        buttonradius1.setColorClick(new java.awt.Color(127, 199, 217));
        buttonradius1.setColorOver(new java.awt.Color(220, 242, 241));
        buttonradius1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buttonradius1.setRadius(50);
        buttonradius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonradius1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonradius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 730, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Desktop - 3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        registerdirekController control = new registerdirekController();
        registerDirectors frame = new registerDirectors(control);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonradius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonradius1ActionPerformed
        // TODO add your handling code here:
        control.login(txtEmail.getText(),txtPass.getText());
    }//GEN-LAST:event_buttonradius1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginDirectors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                logindirekController control = new logindirekController();
                loginDirectors frame = new loginDirectors(control);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Component.buttonradius buttonradius1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
