/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model.direktur;

import Controller.*;
import java.awt.Font;

/**
 *
 * @author Yudo P
 */
public class reportFInance extends javax.swing.JFrame {

    /**
     * Creates new form reportFInance
     */
   private graphicController control;
public reportFInance(graphicController grapcontroller) {
    initComponents();
    control = grapcontroller;
    control.showLineChartIncome(incomePanel);
    control.showLineChartOutcome(outcomePanel);
    control.harianIncome(incomeHarian);
    control.bulananIncome(incomeBulanan);
    control.lostFokus(incomeHarian, incomeBulanan, outcomeHarian, outcomeBulanan);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        outcomePanel = new javax.swing.JPanel();
        incomePanel = new javax.swing.JPanel();
        incomeHarian = new javax.swing.JTextField();
        outcomeBulanan = new javax.swing.JTextField();
        incomeBulanan = new javax.swing.JTextField();
        outcomeHarian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        outcomePanel.setLayout(new java.awt.BorderLayout());
        jPanel1.add(outcomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 120, 760, 570));

        incomePanel.setLayout(new java.awt.BorderLayout());
        jPanel1.add(incomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 760, 580));

        incomeHarian.setFont(new Font("Montserrat", Font.BOLD, 18));
        incomeHarian.setForeground(new java.awt.Color(127, 199, 217));
        incomeHarian.setBorder(null);
        jPanel1.add(incomeHarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 780, 170, 30));

        outcomeBulanan.setFont(new Font("Montserrat", Font.BOLD, 18));
        outcomeBulanan.setForeground(new java.awt.Color(127, 199, 217));
        outcomeBulanan.setBorder(null);
        jPanel1.add(outcomeBulanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 780, 170, 30));

        incomeBulanan.setFont(new Font("Montserrat", Font.BOLD, 18));
        incomeBulanan.setForeground(new java.awt.Color(127, 199, 217));
        incomeBulanan.setBorder(null);
        jPanel1.add(incomeBulanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 780, 170, 30));

        outcomeHarian.setFont(new Font("Montserrat", Font.BOLD, 18));
        outcomeHarian.setForeground(new java.awt.Color(127, 199, 217));
        outcomeHarian.setBorder(null);
        jPanel1.add(outcomeHarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 780, 180, 30));

        jLabel1.setForeground(new java.awt.Color(127, 199, 217));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Desktop - 55.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportFInance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportFInance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportFInance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportFInance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                graphicController control = new graphicController();
                reportFInance frame = new reportFInance(control);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField incomeBulanan;
    private javax.swing.JTextField incomeHarian;
    private javax.swing.JPanel incomePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField outcomeBulanan;
    private javax.swing.JTextField outcomeHarian;
    private javax.swing.JPanel outcomePanel;
    // End of variables declaration//GEN-END:variables
}
