/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model.direktur;

import Controller.*;
import java.awt.Font;
import java.util.Locale;

/**
 *
 * @author Yudo P
 */
public class salaryKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form salaryKaryawan
     */
    private salaryController Control;
    private String user;
    public salaryKaryawan(salaryController controller) {
        this.Control = controller;
        initComponents();
        Control.updateDateTime(tglnow);
        Control.combox1(comboKaryawan);
        Control.tabel(tabelSalary);
    }
     public salaryKaryawan(salaryController controller,String username) {
        this.Control = controller;
        initComponents();
        this.user = username;
        Control.updateDateTime(tglnow);
        Control.combox1(comboKaryawan);
        Control.tabel(tabelSalary);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox1 = new Component.Combobox();
        jPanel1 = new javax.swing.JPanel();
        rekapteam = new Component.buttonradius();
        rekapacara = new Component.buttonradius();
        rekapkeuangan = new Component.buttonradius();
        buttonradius1 = new Component.buttonradius();
        comboKaryawan = new Component.Combobox();
        txtTotaldapat = new javax.swing.JTextField();
        txtTotalpotong = new javax.swing.JTextField();
        tglnow = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSalary = new Component.Table();
        karyawan = new Component.buttonradius();
        buttonradius3 = new Component.buttonradius();
        salary = new Component.buttonradius();
        salaryrecap = new Component.buttonradius();
        jLabel6 = new javax.swing.JLabel();
        absensi = new Component.buttonradius();
        datateam = new Component.buttonradius();
        dataacara = new Component.buttonradius();
        dataclient = new Component.buttonradius();
        finance = new Component.buttonradius();
        txtGajipokok = new javax.swing.JTextField();
        txtTunjangan = new javax.swing.JTextField();
        txtBpjs = new javax.swing.JTextField();
        txtPph = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rekapteam.setBackground(new java.awt.Color(220, 242, 241));
        rekapteam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rekap team.png"))); // NOI18N
        rekapteam.setBorderColor(new java.awt.Color(220, 242, 241));
        rekapteam.setColor(new java.awt.Color(220, 242, 241));
        jPanel1.add(rekapteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 920, 120, 80));

        rekapacara.setBackground(new java.awt.Color(220, 242, 241));
        rekapacara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rekap acara.png"))); // NOI18N
        rekapacara.setBorderColor(new java.awt.Color(220, 242, 241));
        rekapacara.setColor(new java.awt.Color(220, 242, 241));
        jPanel1.add(rekapacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 920, 120, 80));

        rekapkeuangan.setBackground(new java.awt.Color(220, 242, 241));
        rekapkeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rekap keuangan.png"))); // NOI18N
        rekapkeuangan.setBorderColor(new java.awt.Color(220, 242, 241));
        rekapkeuangan.setColor(new java.awt.Color(220, 242, 241));
        jPanel1.add(rekapkeuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 920, 140, 80));

        buttonradius1.setBackground(new java.awt.Color(54, 84, 134));
        buttonradius1.setForeground(new java.awt.Color(255, 255, 255));
        buttonradius1.setText("Create Salary");
        buttonradius1.setToolTipText("");
        buttonradius1.setBorderColor(new java.awt.Color(54, 84, 134));
        buttonradius1.setColor(new java.awt.Color(54, 84, 134));
        buttonradius1.setFont(new Font("Montserrat", Font.BOLD, 20));
        buttonradius1.setRadius(18);
        buttonradius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonradius1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonradius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 410, 70));

        comboKaryawan.setBackground(new java.awt.Color(54, 84, 134));
        comboKaryawan.setBorder(null);
        comboKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        comboKaryawan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih" }));
        comboKaryawan.setSelectedIndex(-1);
        comboKaryawan.setLabeText("Pilih");
        comboKaryawan.setLineColor(new java.awt.Color(54, 84, 134));
        comboKaryawan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboKaryawanItemStateChanged(evt);
            }
        });
        jPanel1.add(comboKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 170, 20));

        txtTotaldapat.setFont(new Font("Montserrat", Font.PLAIN, 20));
        txtTotaldapat.setForeground(new java.awt.Color(54, 84, 134));
        txtTotaldapat.setBorder(null);
        jPanel1.add(txtTotaldapat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 120, 30));

        txtTotalpotong.setFont(new Font("Montserrat", Font.BOLD, 20));
        txtTotalpotong.setForeground(new java.awt.Color(54, 84, 134));
        txtTotalpotong.setBorder(null);
        txtTotalpotong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalpotongActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalpotong, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 120, 30));

        tglnow.setLocale(new Locale("id"));
        tglnow.setBackground(new java.awt.Color(255, 255, 255));
        tglnow.setForeground(new java.awt.Color(255, 255, 255));
        tglnow.setDateFormatString("EEEE, dd MMMM yyyy");
        tglnow.setFont(new Font("Montserrat", Font.PLAIN, 16));
        tglnow.setOpaque(false);
        jPanel1.add(tglnow, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 210, 40));

        tabelSalary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelSalary.setEnabled(false);
        tabelSalary.setFocusable(false);
        tabelSalary.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(tabelSalary);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 1110, 470));

        karyawan.setBackground(new java.awt.Color(127, 199, 217));
        karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/karyawan.png"))); // NOI18N
        karyawan.setBorderColor(new java.awt.Color(127, 199, 217));
        karyawan.setColor(new java.awt.Color(127, 199, 217));
        karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanActionPerformed(evt);
            }
        });
        jPanel1.add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 910, -1, -1));

        buttonradius3.setBackground(new java.awt.Color(127, 199, 217));
        buttonradius3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/karyawan recap.png"))); // NOI18N
        buttonradius3.setBorderColor(new java.awt.Color(127, 199, 217));
        buttonradius3.setColor(new java.awt.Color(127, 199, 217));
        jPanel1.add(buttonradius3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 910, -1, -1));

        salary.setBackground(new java.awt.Color(220, 242, 241));
        salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salary.png"))); // NOI18N
        salary.setBorderColor(new java.awt.Color(220, 242, 241));
        salary.setColor(new java.awt.Color(220, 242, 241));
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        jPanel1.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 920, -1, -1));

        salaryrecap.setBackground(new java.awt.Color(220, 242, 241));
        salaryrecap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salary recap.png"))); // NOI18N
        salaryrecap.setBorderColor(new java.awt.Color(220, 242, 241));
        salaryrecap.setColor(new java.awt.Color(220, 242, 241));
        jPanel1.add(salaryrecap, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 920, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/bg salary.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 910, -1, -1));

        absensi.setBackground(new java.awt.Color(127, 199, 217));
        absensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/absensi.png"))); // NOI18N
        absensi.setBorderColor(new java.awt.Color(127, 199, 217));
        absensi.setColor(new java.awt.Color(127, 199, 217));
        absensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absensiActionPerformed(evt);
            }
        });
        jPanel1.add(absensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 930, -1, -1));

        datateam.setBackground(new java.awt.Color(127, 199, 217));
        datateam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/data team.png"))); // NOI18N
        datateam.setBorderColor(new java.awt.Color(127, 199, 217));
        datateam.setColor(new java.awt.Color(127, 199, 217));
        datateam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datateamActionPerformed(evt);
            }
        });
        jPanel1.add(datateam, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 920, -1, -1));

        dataacara.setBackground(new java.awt.Color(127, 199, 217));
        dataacara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/data acara.png"))); // NOI18N
        dataacara.setBorderColor(new java.awt.Color(127, 199, 217));
        dataacara.setColor(new java.awt.Color(127, 199, 217));
        dataacara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataacaraActionPerformed(evt);
            }
        });
        jPanel1.add(dataacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 920, -1, -1));

        dataclient.setBackground(new java.awt.Color(127, 199, 217));
        dataclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/data client.png"))); // NOI18N
        dataclient.setBorderColor(new java.awt.Color(127, 199, 217));
        dataclient.setColor(new java.awt.Color(127, 199, 217));
        dataclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataclientActionPerformed(evt);
            }
        });
        jPanel1.add(dataclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 920, -1, -1));

        finance.setBackground(new java.awt.Color(127, 199, 217));
        finance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/finance.png"))); // NOI18N
        finance.setBorderColor(new java.awt.Color(127, 199, 217));
        finance.setColor(new java.awt.Color(127, 199, 217));
        jPanel1.add(finance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 920, -1, -1));

        txtGajipokok.setBackground(new java.awt.Color(243, 243, 243));
        txtGajipokok.setForeground(new java.awt.Color(54, 84, 134));
        txtGajipokok.setBorder(null);
        jPanel1.add(txtGajipokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 292, 120, 30));

        txtTunjangan.setBackground(new java.awt.Color(243, 243, 243));
        txtTunjangan.setForeground(new java.awt.Color(54, 84, 134));
        txtTunjangan.setBorder(null);
        txtTunjangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTunjanganKeyReleased(evt);
            }
        });
        jPanel1.add(txtTunjangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 120, 30));

        txtBpjs.setBackground(new java.awt.Color(243, 243, 243));
        txtBpjs.setForeground(new java.awt.Color(54, 84, 134));
        txtBpjs.setBorder(null);
        jPanel1.add(txtBpjs, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 120, 30));

        txtPph.setBackground(new java.awt.Color(243, 243, 243));
        txtPph.setForeground(new java.awt.Color(54, 84, 134));
        txtPph.setBorder(null);
        txtPph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPphKeyReleased(evt);
            }
        });
        jPanel1.add(txtPph, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 120, 30));

        jLabel1.setBackground(new java.awt.Color(235, 235, 235));
        jLabel1.setFont(new Font("Montserrat", Font.BOLD, 20));
        jLabel1.setForeground(new java.awt.Color(54, 84, 134));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Desktop - 15.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboKaryawanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboKaryawanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboKaryawanItemStateChanged

    private void buttonradius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonradius1ActionPerformed
        // TODO add your handling code here:
        Control.cekandconfirmDataSalary(comboKaryawan, txtGajipokok, txtTunjangan, txtBpjs, txtPph, txtTotaldapat, txtTotalpotong, tglnow);
        Control.simpanDataKeExcel(comboKaryawan, tglnow, txtGajipokok, txtTunjangan, txtBpjs, txtPph, txtTotaldapat, txtTotalpotong);
    }//GEN-LAST:event_buttonradius1ActionPerformed

    private void karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanActionPerformed
        // TODO add your handling code here:
        user = "";
        karyawanController karControl = new karyawanController();
        dataKaryawan frame = new dataKaryawan(karControl,user);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_karyawanActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
        user="";
        salaryController salaryControl = new salaryController();
        salaryKaryawan frame = new salaryKaryawan(salaryControl,user);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_salaryActionPerformed

    private void absensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absensiActionPerformed
        // TODO add your handling code here:
        user = "";
        AbsensiController absenControl = new AbsensiController();
        absensiKaryawan frame = new absensiKaryawan(absenControl);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_absensiActionPerformed

    private void datateamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datateamActionPerformed
        // TODO add your handling code here:
        user = "";
        teamController teamControl = new teamController();
        dataTeam frame = new dataTeam(teamControl,user);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_datateamActionPerformed

    private void dataacaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataacaraActionPerformed
        // TODO add your handling code here:
        user = "";
        agendaController agenControl = new agendaController();
        dataAgenda frame = new dataAgenda(agenControl,user);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_dataacaraActionPerformed

    private void dataclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataclientActionPerformed
        // TODO add your handling code here:
        user = "";
        klienController klienControl = new klienController();
        dataKlien frame = new dataKlien(klienControl,user);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_dataclientActionPerformed

    private void txtTotalpotongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalpotongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalpotongActionPerformed

    private void txtTunjanganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTunjanganKeyReleased
        // TODO add your handling code here:
        String gaji = txtGajipokok.getText();
        String tunjang = txtTunjangan.getText();
        
        int totaldapat = Integer.parseInt(gaji)+Integer.parseInt(tunjang);
        txtTotaldapat.setText(String.valueOf(totaldapat));
    }//GEN-LAST:event_txtTunjanganKeyReleased

    private void txtPphKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPphKeyReleased
        // TODO add your handling code here:
        String bpjs = txtBpjs.getText();
        String pph = txtPph.getText();
        
        int totalpotong = Integer.parseInt(bpjs)+Integer.parseInt(pph);
        txtTotalpotong.setText(String.valueOf(totalpotong));
    }//GEN-LAST:event_txtPphKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salaryKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salaryKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salaryKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salaryKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                salaryController control = new salaryController();
                salaryKaryawan frame = new salaryKaryawan(control);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Component.buttonradius absensi;
    private Component.buttonradius buttonradius1;
    private Component.buttonradius buttonradius3;
    private Component.Combobox comboKaryawan;
    private Component.Combobox combobox1;
    private Component.buttonradius dataacara;
    private Component.buttonradius dataclient;
    private Component.buttonradius datateam;
    private Component.buttonradius finance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Component.buttonradius karyawan;
    private Component.buttonradius rekapacara;
    private Component.buttonradius rekapkeuangan;
    private Component.buttonradius rekapteam;
    private Component.buttonradius salary;
    private Component.buttonradius salaryrecap;
    private Component.Table tabelSalary;
    private com.toedter.calendar.JDateChooser tglnow;
    private javax.swing.JTextField txtBpjs;
    private javax.swing.JTextField txtGajipokok;
    private javax.swing.JTextField txtPph;
    private javax.swing.JTextField txtTotaldapat;
    private javax.swing.JTextField txtTotalpotong;
    private javax.swing.JTextField txtTunjangan;
    // End of variables declaration//GEN-END:variables
}
