/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Model.direktur;

import Controller.*;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Yudo P
 */
public class updateAgenda extends javax.swing.JPanel {

    /**
     * Creates new form addAgenda
     */
    private agendaController control;
    public updateAgenda(agendaController controller) {
        initComponents();
        this.control = controller;
        control.combox1(comboCategory);
        control.combox2(comboInstansi);
        control.combox3(comboTeam);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tgl_start = new com.toedter.calendar.JDateChooser();
        txtTotalbiaya = new Component.TextField();
        txtSubharga = new Component.TextField();
        comboCategory = new Component.Combobox();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaInformation = new javax.swing.JTextArea();
        tgl_end = new com.toedter.calendar.JDateChooser();
        comboInstansi = new Component.Combobox();
        comboTeam = new Component.Combobox();
        buttonradius1 = new Component.buttonradius();
        txtNameAcara = new Component.TextField();
        check = new Component.JCheckBoxCustom();
        button1 = new Component.button();
        jLabel1 = new javax.swing.JLabel();

        tgl_start.setBackground(new java.awt.Color(54, 84, 134));
        tgl_start.setForeground(new java.awt.Color(255, 255, 255));

        txtTotalbiaya.setBackground(new java.awt.Color(54, 84, 134));
        txtTotalbiaya.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalbiaya.setLabelText("");

        txtSubharga.setBackground(new java.awt.Color(54, 84, 134));
        txtSubharga.setForeground(new java.awt.Color(255, 255, 255));
        txtSubharga.setLabelText("");
        txtSubharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubhargaKeyReleased(evt);
            }
        });

        comboCategory.setBackground(new java.awt.Color(54, 84, 134));
        comboCategory.setForeground(new java.awt.Color(255, 255, 255));
        comboCategory.setLabeText("");
        comboCategory.setOpaque(false);

        areaInformation.setBackground(new java.awt.Color(54, 84, 134));
        areaInformation.setColumns(20);
        areaInformation.setForeground(new java.awt.Color(255, 255, 255));
        areaInformation.setRows(5);
        jScrollPane1.setViewportView(areaInformation);

        tgl_end.setBackground(new java.awt.Color(54, 84, 134));
        tgl_end.setForeground(new java.awt.Color(255, 255, 255));

        comboInstansi.setBackground(new java.awt.Color(54, 84, 134));
        comboInstansi.setForeground(new java.awt.Color(255, 255, 255));
        comboInstansi.setLabeText("");
        comboInstansi.setOpaque(false);

        comboTeam.setBackground(new java.awt.Color(54, 84, 134));
        comboTeam.setForeground(new java.awt.Color(255, 255, 255));
        comboTeam.setLabeText("");
        comboTeam.setOpaque(false);

        buttonradius1.setBackground(new java.awt.Color(54, 84, 134));
        buttonradius1.setForeground(new java.awt.Color(255, 255, 255));
        buttonradius1.setText("ADD");
        buttonradius1.setBorderColor(new java.awt.Color(222, 229, 228));
        buttonradius1.setColor(new java.awt.Color(54, 84, 134));
        buttonradius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonradius1ActionPerformed(evt);
            }
        });

        txtNameAcara.setBackground(new java.awt.Color(54, 84, 134));
        txtNameAcara.setBorder(null);
        txtNameAcara.setForeground(new java.awt.Color(255, 255, 255));
        txtNameAcara.setLabelText("");

        check.setBackground(new java.awt.Color(222, 229, 228));
        check.setForeground(new java.awt.Color(54, 84, 134));
        check.setText("    Apakah sudah yakin?");
        check.setBorderPainted(true);
        check.setBorderPaintedFlat(true);
        check.setFont(new Font("Montserrat", Font.BOLD, 15));
        check.setOpaque(true);
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        button1.setText("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/updateAgenda.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(comboInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(txtTotalbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(buttonradius1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(tgl_start, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(txtNameAcara, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(txtSubharga, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(comboTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(tgl_end, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(comboInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(txtTotalbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGap(850, 850, 850)
                .addComponent(buttonradius1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(810, 810, 810)
                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(tgl_start, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(txtNameAcara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(txtSubharga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(comboTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(710, 710, 710)
                .addComponent(tgl_end, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonradius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonradius1ActionPerformed
        // TODO add your handling code here:
        String nomer = "KP-1.2/CV.MKN-18.1/IV/2024";
         if(check.isSelected()){
       control.updateAgenda(txtNameAcara, areaInformation, txtSubharga, tgl_end, tgl_end, comboTeam, comboInstansi, comboTeam);
       control.updateFinance(txtNameAcara, areaInformation, txtSubharga, tgl_end, tgl_end);
        }else{
            JOptionPane.showMessageDialog(null, "CHECKLIST DAHULU !", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_buttonradius1ActionPerformed

    private void txtSubhargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubhargaKeyReleased
        // TODO add your handling code here:
        String sub = txtSubharga.getText();
int subharga = Integer.parseInt(sub);
double pajak = subharga * 0.11; // Menghitung pajak (11% dari subtotal)
double totalharga = subharga + pajak; // Menambahkan pajak ke subtotal untuk mendapatkan total biaya
txtTotalbiaya.setText(String.valueOf(totalharga));

    }//GEN-LAST:event_txtSubhargaKeyReleased

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea areaInformation;
    private Component.button button1;
    public Component.buttonradius buttonradius1;
    private Component.JCheckBoxCustom check;
    public Component.Combobox comboCategory;
    public Component.Combobox comboInstansi;
    public Component.Combobox comboTeam;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public com.toedter.calendar.JDateChooser tgl_end;
    public com.toedter.calendar.JDateChooser tgl_start;
    public Component.TextField txtNameAcara;
    public Component.TextField txtSubharga;
    public Component.TextField txtTotalbiaya;
    // End of variables declaration//GEN-END:variables
}
