/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import Controller.logindirekController;
import Model.direktur.*;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Yudo P
 */
public class DashboardUtama extends javax.swing.JFrame {

    /**
     * Creates new form DashboardUtama
     */
    public DashboardUtama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    public  boolean stat ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        switchButton2 = new Component.SwitchButton();
        button1 = new Component.button();
        button2 = new Component.button();
        dashutama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        switchButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchButton2MouseClicked(evt);
            }
        });
        getContentPane().add(switchButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 220, 90, 40));

        button1.setBackground(new java.awt.Color(220, 242, 241));
        button1.setBorder(null);
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Group 30.png"))); // NOI18N
        button1.setBorderColor(new java.awt.Color(220, 242, 241));
        button1.setBorderPainted(false);
        button1.setColor(new java.awt.Color(220, 242, 241));
        button1.setColorClick(new java.awt.Color(204, 204, 204));
        button1.setColorOver(new java.awt.Color(204, 204, 204));
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 650, 150, 180));

        button2.setBackground(new java.awt.Color(220, 242, 241));
        button2.setBorder(null);
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Group 29.png"))); // NOI18N
        button2.setBorderColor(new java.awt.Color(220, 242, 241));
        button2.setBorderPainted(false);
        button2.setColor(new java.awt.Color(220, 242, 241));
        button2.setColorClick(new java.awt.Color(204, 204, 204));
        button2.setColorOver(new java.awt.Color(204, 204, 204));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 650, -1, -1));

        dashutama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Desktop - 2 (1).png"))); // NOI18N
        dashutama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(dashutama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1920, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void switchButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchButton2MouseClicked
        // TODO add your handling code here:
       int a =1;
       if(a==1){
           if(stat != true){
            ImageIcon icon = new ImageIcon("src\\resource\\Desktop - 22.png");
            dashutama.setIcon(icon);
            stat=true;
          }else{
             ImageIcon icon1 = new ImageIcon("src\\resource\\Desktop - 2 (1).png");
            dashutama.setIcon(icon1);
            stat=false;
           }
       }
       

    }//GEN-LAST:event_switchButton2MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        logindirekController control = new logindirekController();
                loginDirectors frame = new loginDirectors(control);
                frame.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Component.button button1;
    private Component.button button2;
    public javax.swing.JLabel dashutama;
    private Component.SwitchButton switchButton2;
    // End of variables declaration//GEN-END:variables
}
