/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model.karyawan;

import Connection.*;
import Controller.*;
import java.awt.event.*;
import java.io.*;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.*;
import java.util.Locale;
import javax.swing.*;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;



/**
 *
 * @author Yudo P
 */
public class absensiKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form absensiKaryawan
     */
    private AbsensiController control;

    public absensiKaryawan(AbsensiController controller) {
        this.control = controller; // Assign the provided controller instance
        initComponents();
        control.updateDateTime(tglnow, timenow);
        control.startTimer(tglnow, timenow);
    }

    

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        jabatan = new javax.swing.JTextField();
        jamabsen = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        tglnow = new javax.swing.JTextField();
        timenow = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setText("jTextField1");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 420, 300, 50));

        nik.setText("jTextField1");
        getContentPane().add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 480, 300, 40));

        jabatan.setText("jTextField1");
        getContentPane().add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 530, 300, 40));

        jamabsen.setText("jTextField1");
        getContentPane().add(jamabsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 580, 300, 40));

        status.setText("jTextField1");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 630, 300, 40));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 370, 300, 40));

        tglnow.setText("jTextField1");
        getContentPane().add(tglnow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 100, 250, 50));

        timenow.setText("jTextField1");
        getContentPane().add(timenow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 150, 310, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/absensi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        // TODO add your handling code here:
                                    
    // TODO add your handling code here:
    if(id.getText().isEmpty()){
        id.setFocusable(true);
    } else {
        // Panggil metode getIdteam() dari objek control saat key release terjadi
        control.getIdteam(id, name, nik, jabatan, jamabsen, status);
        control.simpanDataKeExcel(name.getText(), tglnow.getText(), status.getText());
        id.setFocusable(false);
        name.setFocusable(false);
        nik.setFocusable(false);
        jabatan.setFocusable(false);
        jamabsen.setFocusable(false);
        status.setFocusable(false);
    }


    }//GEN-LAST:event_idKeyReleased

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            AbsensiController controller = new AbsensiController();
            absensiKaryawan frame = new absensiKaryawan(controller);
            frame.setVisible(true);
        }
    });
}





    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField jabatan;
    public javax.swing.JTextField jamabsen;
    public javax.swing.JTextField name;
    public javax.swing.JTextField nik;
    public javax.swing.JTextField status;
    public javax.swing.JTextField tglnow;
    public javax.swing.JTextField timenow;
    // End of variables declaration//GEN-END:variables
}
